#!/bin/bash -e

dest_prefix=/home/flashrom/cross-libs
lib_src=/home/flashrom/download/libs/pciutils-3.1.5

#. buildbot.conf

old=`pwd`
cd ${lib_src}

for triplet in mips-linux-gnu sparc-linux-gnu powerpc-linux-gnu powerpc64le-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu i386-linux-gnu; do
	prefix=${triplet}-
	arch=${triplet%-*}
	echo -n $triplet
	if [ -e ${dest_prefix}/${triplet}/lib/libpci.a ] ; then
		echo " exists already, skipping."
		continue
	fi
	make distclean 1>/dev/null 2>&1
	make HOST=${arch} CROSS_COMPILE=${prefix} PREFIX= DESTDIR=${dest_prefix}/${triplet} ZLIB=no DNS=no install install-lib  1>/dev/null 2>&1
	echo " successfully installed."
done

cd "$old"

#cat << EOF > ~/local/share/config.site
#CPPFLAGS=-I$HOME/local/include
#LDFLAGS=-L$HOME/local/lib
#...
#EOF

#./autogen.sh --disable-debug-log --host=i386-linux-gnu --prefix=/home/flashrom/cross-libs/i386-linux

# libusb-compat-0.1
# PKG_CONFIG_PATH=/home/flashrom/cross-libs/i386-linux/lib/pkgconfig ./autogen.sh --disable-debug-log --host=i386-linux-gnu --prefix=/home/flashrom/cross-libs/i386-linux