#!/bin/bash

. /home/flashrom-buildbot/buildbot/handle_vbox_vm.sh

echo "Running in $(pwd)"
case "$2" in
	i386-openbsd-gcc)
		handle_vbox_vm start OpenBSD-i386 192.168.56.11 "halt -p" || exit 1
		tar czf - . | ssh compiler@192.168.56.11 "mkdir -p ~/buildbot/$1; cd ~/buildbot/$1; tar xzf -"
		;;
	amd64-netbsd-gcc)
		handle_vbox_vm start NetBSD-6.1-amd64 192.168.56.10 /sbin/poweroff || exit 1
		tar czf - . | ssh compiler@192.168.56.10 "mkdir -p ~/buildbot/$1; cd ~/buildbot/$1; tar xzf -"
		;;
	amd64-dragonflybsd-gcc)
		handle_vbox_vm start DragonFlyBSD-3.4.2-amd64 192.168.56.12 "halt -p" || exit 1
		tar czf - . | ssh compiler@192.168.56.12 "mkdir -p ~/buildbot/$1; cd ~/buildbot/$1; tar xzf -"
		;;
	*)
		;;
esac
