#!/bin/bash

. /home/flashrom-buildbot/buildbot/handle_vbox_vm.sh

instance="$1"
compiler="$2"
shift 2
case "$compiler" in
	i386-openbsd-gcc)
		handle_vbox_vm stop OpenBSD-i386 192.168.56.11 "halt -p" || exit 1
		;;
	amd64-netbsd-gcc)
		handle_vbox_vm stop NetBSD-6.1-amd64 192.168.56.10 /sbin/poweroff || exit 1
		;;
	*)
		;;
esac
