#!/bin/bash -e

. buildbot.conf

lib_src=$(realpath ../libs/pciutils)

old=`pwd`
cd ${lib_src}

for triplet in \
	aarch64-linux-gnu \
	arm-linux-gnueabihf \
	i386-linux-gnu \
	mips-unknown-linux-gnu \
	powerpc64le-linux-gnu \
	powerpc-linux-gnu \
	sparc-unknown-linux-gnu \
	x86_64-linux-gnux32 \
	x86_64-apple-darwin15 \
	x86_64-unknown-linux-musl \
	x86_64-unknown-linux-uclibc \
	; do
	prefix=${triplet}-
	arch=${triplet%-*}
	echo -n $triplet
	if [ -e ${libs_base}/${triplet}/lib/libpci.a ] ; then
		echo " exists already, skipping."
		continue
	fi
	echo
	if [ "$triplet" = "x86_64-apple-darwin15" ]; then
		export CC="${triplet}-clang" CXX="${triplet}-clang++"
	else
		export CC="${triplet}-gcc" CXX="${triplet}-g++"
	fi
	make distclean
	make STRIP="-s --strip-program=${triplet}-strip" CC=${CC} CXX=${CXX} HOST=${arch} CROSS_COMPILE=${prefix} PREFIX= DESTDIR=${libs_base}/${triplet} ZLIB=no DNS=no SHARED=no all install-lib
	echo " successfully installed."
done

cd "$old"
