#!/bin/bash -e

. buildbot.conf

libusb_src=$(realpath ../libs/libusb)
libusb_compat_src=$(realpath ../libs/libusb-compat-0.1)

old=`pwd`

buildarch=`gcc -dumpmachine 2>/dev/null`
if [ -z "$buildarch" ]; then
	eval `dpkg-architecture`
	if [ -z $DEB_HOST_GNU_TYPE ]; then
		printf "Could not determine host architecture\n\n"
		exit 1
	fi
	buildarch="$DEB_HOST_GNU_TYPE"
fi

# NB: Windows is special. To build libusb-win32 from source one needs a windows machine and sdk...
for triplet in x86_64-unknown-linux-uclibc x86_64-unknown-linux-musl mips-unknown-linux-gnu sparc-unknown-linux-gnu powerpc-linux-gnu powerpc64le-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu i386-linux-gnu; do
	printf $triplet

	if [ -e ${libs_base}/${triplet}/lib/libusb-1.0.a -a -e ${libs_base}/${triplet}/lib/libusb.la ] ; then
		echo " exists already, skipping."
		continue
	fi
	# libusb first
	cd ${libusb_src}
	if [ -e Makefile ]; then
		make distclean
	fi
	./autogen.sh --disable-debug-log --host=${triplet} --build="$buildarch" --prefix=${libs_base}/${triplet}/
	make install

	# libusb-compat afterwards
	cd ${libusb_compat_src}
	if [ -e Makefile ]; then
		make distclean
	fi
	PKG_CONFIG_PATH=${libs_base}/${triplet}/lib/pkgconfig ./autogen.sh --disable-debug-log --host=${triplet} --build="$buildarch" --prefix=${libs_base}/${triplet}
	make install
	printf " successfully installed.\n"
done

cd "$old"
