#!/bin/bash -e

. buildbot.conf

libftdi0_root=$(realpath ../libs/libftdi0)

old=`pwd`
cd ${libftdi0_root}

buildarch=`gcc -dumpmachine 2>/dev/null`
if [ -z "$buildarch" ]; then
	eval `dpkg-architecture`
	if [ -z $DEB_HOST_GNU_TYPE ]; then
		printf "Could not determine host architecture\n\n"
		exit 1
	fi
	buildarch="$DEB_HOST_GNU_TYPE"
fi

# FIXME: x86_64-linux-gnux32
for triplet in x86_64-linux-android i686-w64-mingw32 x86_64-w64-mingw32 x86_64-unknown-linux-uclibc x86_64-unknown-linux-musl mips-unknown-linux-gnu sparc-unknown-linux-gnu powerpc-linux-gnu powerpc64le-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu i386-linux-gnu; do
	printf $triplet

	if [ -e ${libs_base}/${triplet}/lib/libftdi.a ] ; then
		echo " exists already, skipping."
		continue
	fi

	if [ $triplet = "i686-w64-mingw32" -o $triplet = "x86_64-w64-mingw32" ]; then
		export CPPFLAGS='-DENODATA=EIO'
	else
		export CPPFLAGS=
	fi

	if [ -e Makefile ]; then
		make distclean
	fi

	export PKG_CONFIG_LIBDIR=${libs_base}/${triplet}/lib/pkgconfig
	./configure --host=${triplet} --build="$buildarch" --prefix=${libs_base}/${triplet}/ --exec-prefix=${libs_base}/${triplet}/ --without-examples
	make install

	printf " successfully installed.\n"
done

cd "$old"
