#!/bin/bash

##########
# Debian #
##########

apt-get build-dep flashrom
apt-get install linux-libc-dev:i386 clang gcc-mingw-w64 gcc-multilib gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-powerpc64le-linux-gnu  gcc-powerpc-linux-gnu

# does not work
#apt-get install emdebian-archive-keyring
#echo 'deb http://emdebian.org/debian/ unstable main' > /etc/apt/sources.list.d/emdebian.list
#apt-get update
#apt-get install gcc-4.7-sparc-linux-gnu gcc-4.7-sparc64-linux-gnu gcc-4.7-mips-linux-gnu gcc-4.7-mipsel-linux-gnu
