#!/bin/bash
sudo zypper addrepo http://download.opensuse.org/repositories/home:fstrba:msdos/openSUSE_12.2/home:fstrba:msdos.repo
sudo zypper install djgpp-gcc
sudo zypper addrepo http://download.opensuse.org/repositories/windows:mingw:win64/openSUSE_12.2/windows:mingw:win64.repo
sudo zypper install mingw64-cross-gcc
sudo zypper addrepo http://download.opensuse.org/repositories/windows:mingw:win32/openSUSE_12.2/windows:mingw:win32.repo
sudo zypper install mingw32-cross-gcc
sudo zypper addrepo http://download.opensuse.org/repositories/home:duwe:crosstools/openSUSE_12.2/home:duwe:crosstools.repo
sudo zypper in cross-arm-linux-gnueabi-gcc cross-mips-linux-gcc cross-ppc-linux-gnueabi-gcc
sudo zypper in cross-arm-linux-gnueabi-kernel-headers cross-mips-linux-kernel-headers cross-ppc-linux-gnueabi-kernel-headers
sudo zypper in cross-arm-linux-gnueabi-glibc cross-mips-linux-glibc cross-ppc-linux-gnueabi-glibc
