#!/bin/bash -e

#dryrun="echo"

usage () {
	echo "$0 <vmname>"
	exit 1
}

if [ $# -ne 1 ]; then
	usage
fi

. buildbot.conf
. common.sh

vmname=$1

fill_vbox_arrs

unset compiler
for ck in "${!available_compilers[@]}"; do
	curvmname=${vbox_names[$ck]}
	[ -z "$curvmname" ] && continue
	[ "$curvmname" != "$vmname" ] && continue
	if ! vboxmanage showvminfo "${vmname}" >/dev/null; then
		msg_err "There is apparently no VM named $vmname."
	fi
	compiler=$ck
done

if [ -z "$compiler" ]; then
	msg_err "Could not find compiler name of VM $vmname".
fi

echo "Compiler $compiler matches VM $vmname."

if VBoxManage list runningvms|grep -q "${vmname}"; then
	$dryrun VBoxManage controlvm "$vmname" poweroff
fi

$dryrun VBoxManage unregistervm "$vmname" --delete # deletes hdd images, states, configs as well

if [ -z "${vbox_hostonlyifs[$compiler]}" ]; then
	echo "No hostonlyif found belonging to VM $vmname"
else
	echo "Removing hostonlyif "${vbox_hostonlyifs[$compiler]}" belonging to VM $vmname"
	$dryrun VBoxManage dhcpserver remove --netname "HostInterfaceNetworking-${vbox_hostonlyifs[$compiler]}"
	$dryrun VBoxManage hostonlyif remove "${vbox_hostonlyifs[$compiler]}"
fi
