#! /bin/bash

. buildbot.conf

save_vm () {
	local vmname="$1"
	if ! VBoxManage list runningvms|grep -q "${vmname}"; then
		echo "${vmname} VM is already stopped. Nothing done."
		return 0
	fi
	VBoxManage controlvm "${vmname}" savestate 2>/dev/null
	if [ "$?" -eq 0 ]; then
		echo "Saved ${vmname} VM successfully"
	else
		echo "Saving ${vmname} VM failed"
	fi
}

for vmname in ${vbox_names[@]} ; do
	save_vm ${vmname} &
done
wait
