#!/bin/bash

. buildbot.conf
. common.sh
. vmcmd_helpers.sh

validate_vmcmd_args "$@"
echo "Trying to savestate ${vmcmd_vmnames[@]}."
fill_vbox_arrs

save_vm () {
	local vmname
	local ck
	get_ck_and_vmname "$1" "vmname" "ck"
	if ! VBoxManage list runningvms|grep -q "^\"${vmname}\""; then
		echo "${vmname} VM is already stopped. Nothing done."
		return 0
	fi
	VBoxManage controlvm "${vmname}" savestate 2>/dev/null
	if [ "$?" -eq 0 ]; then
		echo "Saved ${vmname} VM successfully"
	else
		echo "Saving ${vmname} VM failed"
	fi
}

for vmname in ${vmcmd_vmnames[@]} ; do
	save_vm ${vmname} &
done
wait
