#!/bin/bash

. buildbot.conf
. common.sh
. vmcmd_helpers.sh

validate_vmcmd_args "$@"
echo "Trying to shutdown ${vmcmd_vmnames[@]}."
fill_vbox_arrs

for vmname in ${vmcmd_vmnames[@]} ; do
	shutdown_vm ${vmname}
done
wait
